---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: docker.io/rajasur90/flask-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: db_name
              value: flaskapi
            - name: db_name
              value: flaskapi
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE_PORT
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE_HOST


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000 
  selector:
    app: flaskapi
  type: LoadBalancer
