---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: docker.io/rajasur90/flask-demo-prj:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: db_name
              value: Food
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE_PORT
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: flaskapi
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000 
  type: NodePort
  selector:
    app: flaskapi