apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-python-app
  labels:
    release: prometheus 
    app: flaskapi
  namespace: monitoring
spec:
  endpoints:  
  - path: http://192.168.49.2:32000/metrics
    port: sap
    targetPort: 5000
  namespaceSelector:
    matchNames:
    - application
  selector:
    matchLabels:
      app: flaskapi 